name: Build Flamerobin for Windows

env: 
  wx-tag-version: v3.2.2.1
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: wxWidget cache
      id: cache-wxwidget
      uses: actions/cache@v3
      with:
        path: |
            wxWidgets
        key: ${{ runner.os }}-wxwidgets-${{env.wx-tag-version}}
        restore-keys: ${{ runner.os }}-wxwidgets-${{env.wx-tag-version}}
    
    - uses: actions/checkout@v3
    
    - if: ${{ steps.cache-wxwidget.outputs.cache-hit != 'true' }}
      continue-on-error: true
      name: clone wxWidgets
      run:  git clone --recursive --branch ${{env.wx-tag-version}} --depth 1 https://github.com/wxWidgets/wxWidgets.git
      
    - if: ${{ steps.cache-wxwidget.outputs.cache-hit != 'true' }}
      continue-on-error: true
      name: replace /MD for /MT
      run: 
             $xmls = (Get-ChildItem -Path "wxWidgets\build\msw" -Recurse -Filter *.vcxproj).FullName ;
             foreach ($xml in $xmls) {
               echo $xml;
               (Get-Content $xml).replace("MultiThreadedDebugDLL", "MultiThreadedDebug") | Set-Content $xml ;
               (Get-Content $xml).replace("MultiThreadedDLL", "MultiThreaded") | Set-Content $xml
             }

    - if: ${{ steps.cache-wxwidget.outputs.cache-hit != 'true' }}
      continue-on-error: true
      name: Build wxWidgets x86
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && 
        dir
        rem msbuild.exe wxWidgets\build\msw\wx_vc17.sln /t:Build /p:Configuration=Release /p:Platform=Win32
        
#    - if: ${{ steps.cache-wxwidget.outputs.cache-hit != 'true' }}
#      continue-on-error: true
#      name: Build wxWidgets x64
#      shell: cmd
#      run: |
#        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && msbuild.exe wxWidgets\build\msw\wx_vc17.sln /t:Build /p:Configuration=Release /p:Platform=x64

    - name: look for folder
      run: >
        dir &&
        dir .. &&
        dir D:/a/_temp/ &&
        "C:\Program Files\Git\usr\bin\tar.exe" -xvf D:/a/_temp/*/cache.tzst -P -C D:/a/FlamerobinActionTests/FlamerobinActionTests --force-local --use-compress-program "zstd -d"
        
        
    - name: Build Flamerobin x86
      if: false
      run: >
        dir &&
        dir wxWidgets &&
        dir wxWidgets\lib &&
        cmake -S .\ -B .\Build32 -A Win32 -DWXDIR=wxWidgets &&
        cmake --build .\Build32 --config Release -j 8
        
 #   - name: Build Flamerobin x64
 #     run: >
 #       cmake -S .\ -B .\Build64 -A x64 -DWXDIR=wxWidgets &&
 #       cmake --build .\Build64 --config Release -j 8

    - name: Innosetup 
      if: false
      run: >
        ISCC.exe install\win32\FlameRobinSetup.iss
        
#    - name: Innosetup64
#      run: >
#        ISCC.exe install\win32\FlameRobinSetup.iss

#    - name: Upload installer
#      uses: actions/upload-artifact@main
#      with:
#          name: flamerobin-instaler
#          path: install/win32/output/flamerobin-*.exe
